### ISSUE TITLE
Consider adding an `attrs`-like converter macro?

### ISSUE THREAD

**Issue by singularitti** [mauro3/Parameters.jl#100]
I was using [`attrs`](https://www.attrs.org/en/stable/) in Python. It shares a similar functionality as `Parameters.jl`. However, one thing it has is not supported by `Parameters.jl` now---the default [converter](https://www.attrs.org/en/stable/init.html#converters). It is often the case that users do not supply the right type of parameters to the constructor. I want that we can handle this if they do not give the right type instead of throwing an error.
Here is an example:
```julia
struct A
   mass::Int
   velocity::String
   coordinate::Vector{Pair{Int, Float64}}
   time::NTuple{3, Float64}
   frequency::Float64
end
```
For some reason, I want to handle if a user supplies a `Vector{Float64}` or a `NTuple{N,Float64}` to the `coordinate` field, the construct `A` could directly converts it to a `Vector{Pair{Int, Float64}}`, by calling a function
```julia
convertfield(x::Vector{Pair{Int, Float64}}) = x
function convertfield(x::Union{AbstractVector{<: Real}, NTuple{N, <: Real} where {N}})
    return collect(pairs(Float64.(x)))
end
```
on it. The syntax could be like
```julia
@with_kw struct A
   mass::Int
   velocity::String
   coordinate::Vector{Pair{Int, Float64}} = ones(3); @convert convertfiled(coordinate); @assert length(coordinate) == 3
   time::NTuple{3, Float64}
   frequency::Float64
end
```
where `@convert` is a macro that takes a function. I could write something like
```julia
@with_kw struct A
   mass::Int
   velocity::String
   coordinate::Vector{Pair{Int, Float64}} = collect(pairs(ones(3)))
   time::NTuple{3, Float64}
   frequency::Float64
end
```
But it is just a default value, not a converter.

**Comment by mauro3** [comment]
I am not really interested in supporting this as it is too much of a feature creep to me.

Maybe some sort of plug-in system should be made, so you can do this personally.  Not sure what this could look like.
