### ISSUE TITLE
Cannot use with_kw as part of a macro

### ISSUE THREAD

**Issue by christopher-dG** [mauro3/Parameters.jl#104]
I'm not really sure if I'm just using Julia's macro system wrong or if this is something that can be fixed here -- if it's the former feel free to close.

```jl
julia> module Foo
       using Parameters: with_kw
       macro foo(ex::Expr)
           return with_kw(ex, __module__, false)
       end
       end
Main.Foo

julia> Foo.@foo struct Bar
         x::Int = 1
       end
ERROR: syntax: invalid macro definition
Stacktrace:
 [1] top-level scope at REPL[2]:1
```

Basically I want to write a macro that does Parameters' `@with_kw_noshow` to create the struct, and additionally generates some other methods for the struct.

**Comment by mauro3** [comment]
The output of `with_kw` needs to be escaped:
```
julia> module Foo
              using Parameters: with_kw
              macro foo(ex::Expr)
                  return esc(with_kw(ex, __module__, false))
              end
              end
WARNING: replacing module Foo.
Main.Foo

julia> Foo.@foo struct Bar
                x::Int = 1
              end
Bar
```

I'll close this but feel free to post more here or re-open.

**Comment by christopher-dG** [comment]
Welp, I thought I had tried every permutation of escaping various parts of the expression in my experiments... But I guess I never tried just escaping the whole thing :upside_down_face:  Thank you for the quick response!
