### ISSUE TITLE
Add `FieldDefaults.jl` to README.md?

### ISSUE THREAD

**Issue by singularitti** [mauro3/Parameters.jl#106]
There is another package that implements default fields: [`FieldDefaults.jl`](https://github.com/rafaqz/FieldDefaults.jl). It can be combined with [`FieldMetadata.jl`](https://github.com/rafaqz/FieldMetadata.jl) or [`Flatten.jl`](https://github.com/rafaqz/Flatten.jl). Could you please add them to `README.md`?

**Comment by mauro3** [comment]
Sure, just do a PR.

**Comment by singularitti** [comment]
Sure, see #108.
