### ISSUE TITLE
@pack_MyType

### ISSUE THREAD

**Issue by phlavenk** [mauro3/Parameters.jl#107]
As I understand how the new @pack_* works:
```julia
@with_kw struct MM
    r = "val_def"
    a = "cnt_def"
end
m = @pack_MM #error, r not defined
r= "val_1"
a = "cnt_2"
m = @pack_MM  #OK
```
I'm missing the functionality where I could just tell the macro which variables to pack - the same way the @pack! macro works
```julia
@pack_MM m_new = a #use a and default r
```
Is that a complex task to incorporate into current code? I admit I don't understand the meta-programming so I have no idea how difficult such change is.

**Comment by mauro3** [comment]
Why not just
```
m = MM(a=a)
```
or if you have an `m` already
```
m_new = MM(m, a=a)
```
Also, look into Setfield.jl.

So, I'll close this.  But let me know if you think this is not addressed properly.
