### ISSUE TITLE
Split at-pack and at-unpack into a separate package

### ISSUE THREAD

**Issue by mauro3** [mauro3/Parameters.jl#109]
These two macros seem to get a good bit of usage without the rest.  @tpapp is such a user, I think.  Thoughts?  Package name `UnPack.jl`.

**Comment by tpapp** [comment]
I support the idea and like the name. This package has some dependencies which I guess are not necessary for these two macros.

**Comment by mauro3** [comment]
Here it is https://github.com/mauro3/UnPack.jl

Any other thoughts, anyone?

**Comment by tpapp** [comment]
I love how lean the package is.

**Comment by mauro3** [comment]
Too lean, almost leftpad...

**Comment by tpapp** [comment]
:smile: If you are referring to the left-pad debacle for npm, I don't think that is a concern for Julia. But if you don't want to factor it out to another package, I respect that decision too.

For me, `@unpack` serves the same purpose as [`common-lisp:with-slots`](http://clhs.lisp.se/Body/m_w_slts.htm). It is indeed a very simple macro, but very useful.

**Comment by mauro3** [comment]
Yes, the npm one, but that was just tongue in cheek. I think it makes sense here too.  I'll go ahead and register it in the next few days.

**Comment by mauro3** [comment]
Here we go: https://github.com/JuliaRegistries/General/pull/6234

**Comment by goretkin** [comment]
Thanks for splitting this out! I hadn't noticed `UnPack.jl` existed until `Pkg.update()` showed `+ UnPack v1.0.0`

**Comment by mauro3** [comment]
Cool.

I guess I forgot to close this...
