### ISSUE TITLE
function level unpack like macro

### ISSUE THREAD

**Issue by gabrielgellner** [mauro3/Parameters.jl#11]
A while ago I started making a package that was doing basically what this package is doing (with though oh so similar name Param.jl ... I have since used your package as it is better). It is barely a prototype in comparison but one feature I miss while using `Parameters.jl` is a simple macro I made used as follows
```jl
@withparam TypeName par function(t, y, par::TypeName)
end
```
where inside the function any instance of a fieldname in the type `TypeName` would be replaced as `par.fieldname`, so the natural way of writing the equations could be used.

The code is crazy simple, and might not be as robust as would be needed, but would there be interest in this usauge?

For the implementation see:
[github Param.jl](https://github.com/gabrielgellner/Param)

**Comment by mauro3** [comment]
If I understand `@withparam` correctly, then this is already provided with the slightly different syntax:
```
function f(t, y, par::TypeName)
    @unpack_TypeName par
    ....
end
```
(Although, I now prefer to use the `@(un)pack` macros: https://parametersjl.readthedocs.io/en/latest/manual/#unpack-macros)

Thanks for your interest!  And maybe the package name is not so bad after all (see PR #3)...

**Comment by gabrielgellner** [comment]
Yeah I guess it is just habit. I new about the `@unpack` macro I just didn't like doing it inside of the function definition (and my version actually changes the AST not just making variable definitions (it is more like a Mathematica replacement of the variables in the type), hence why it needs to take the function definition as an argument).

I will try to use the more idiomatic `Parameter.jl` way and see if I can get used to it.

Maybe once 0.5 is out we can make `@unpack` generic so that the ugly `@unpack_TYPE` versions aren't need ;)

Thanks for the great packages!

**Comment by mauro3** [comment]
I want to keep the `@(un)pack` as it is, as the `@unpack_*` macros are quite dangerous (see the manual for two examples, which both bit me).  In fact I quite like the `@unpack` as a nice middle ground between having all parameters as function arguments (explicit but annoying and hard to update) and just blindly unpacking all parameters.  Consider this example: all nicely explicit but without much hassle:
```julia
type Para
    ...
    p_n
    ...
    p_m
    ....
end
function f(x,y,p::Para)
    @unpack p: p_n, p_m
    ...
end
```

I think your `@withparam` suffers the same pitfalls as `@unpack_*`, plus it uses an eval inside the macro, which should be avoided (they say).

Thanks for using Parameters.jl.  I'll close this but feel free to re-open if you feel it is not resolved.
