### ISSUE TITLE
Doesn't quite cooperate with FixedSizeArrays

### ISSUE THREAD

**Issue by stephancb** [mauro3/Parameters.jl#12]
(might of course rather to be fixed there):
```
julia> using FixedSizeArrays,Parameters

julia> @with_kw immutable Probes{T} <: FixedVectorNoTuple{2, T}
           p1::T
           p2::T
           function Probes(t::NTuple{2, T}) #needs to be like this to keep constructor code sane
               new{T}(t[1], t[2])
           end
       end
ERROR: AssertionError: a.head == :(::)

julia> immutable Probes{T} <: FixedVectorNoTuple{2, T}
           p1::T
           p2::T
           function Probes(t::NTuple{2, T}) #needs to be like this to keep constructor code sane
               new{T}(t[1], t[2])
           end
       end
```
(edit by @mauro3: added triple backticks ``` to quote code. Please use those next time ;-)

**Comment by mauro3** [comment]
There are two things here, a bug on my side and one on yours: mine is a parsing error in the macro, I'll look into this.  A work around is to use a one-liner function:
```
julia> @with_kw immutable Probes{T} <: FixedVectorNoTuple{2, T}
                  p1::T
                  p2::T
                  Probes(t::NTuple{2, T})= new{T}(t[1], t[2])
              end
```



However, even if it works, your example cannot work.  The [manual](https://parametersjl.readthedocs.io/en/latest/manual/) says:
```
Custom inner constructors can be defined as long as:
 - one defining all positional arguments is given
 - no zero-positional arguments constructor is defined (as that would clash with the keyword constructor)
 - no @asserts (as in above example) are used within the type body.
```
So you need to additionally add this inner constructor
```
Probes(p1,p2) = new(p1,p2)
```

**Comment by stephancb** [comment]
Thanks, my example is actually not an issue any more. The extra inner constructor seems not needed any more in an up-to-date FixedSizeArrays package, I was not using the newest version. Sorry about this.

**Comment by mauro3** [comment]
Well, it's still a bug on my side, so thanks for reporting!
