### ISSUE TITLE
Release 1.0?

### ISSUE THREAD

**Issue by Datseris** [mauro3/Parameters.jl#121]
Hi there,
I was just about to add this package as a dependency to a package I am developing, but I realized I don't want to do that if it isn't 1.0.

The API has been stable for quite some time now, is there a reason for the absence of 1.0?

Can you please consider tagging 1.0?

**Comment by Datseris** [comment]
Ah actually I just saw https://github.com/mauro3/UnPack.jl and in fact this is what I should consider adding as a dependency, because I only wanted `@unpack/pack`. But since it is so small I'll just copy the source and the license. 

But this issue should remain open, if this package has stable api then 1.0 should be considered.

**Comment by mauro3** [comment]
Yes, I've been meaning to integrate it more closely with `Base.@kwdef`, which might entail some small, slightly breaking changes.  But I haven't found the time yet, so maybe I should do 1.0, and then 2.0.

**Comment by mauro3** [comment]
Also UnPack.jl should be 1.0

**Comment by Datseris** [comment]
> Also UnPack.jl should be 1.0 

That would be very nice if you can do it. We were just discussing of including `UnPack` in DrWatson and exporting the two macros, but I am arguing that I am actively trying to avoid non-1.0 dependencies.

**Comment by mauro3** [comment]
Done for UnPack (my first 1.0 release!)
