### ISSUE TITLE
Create Parameter type without specifying a name

### ISSUE THREAD

**Issue by ChrisRackauckas** [mauro3/Parameters.jl#17]
It would be nice to be able to do:

``` julia
p = @with_kw type # could also be immutable
    a::Int = 6
    b::Float64 = -1.1
    c::UInt8
end
```

and have it silently create a parameter type and return and instance of that type. The tool for doing this is described here: http://stackoverflow.com/questions/39485715/julia-design-silently-defining-naming-types-in-macros/39493415?noredirect=1#comment66311481_39493415. This could be helpful when all you care about is getting a type for its fields, but don't plan on making it again (and it's easier than coming up with arbitrary names all the time).

**Comment by mauro3** [comment]
I guess that would be a poor man's named tuple.  See https://github.com/blackrock/NamedTuples.jl, https://github.com/JuliaLang/julia/pull/16580.  Could be useful.  But you're example would error as `c` does not have a (default) value, right?

**Comment by ChrisRackauckas** [comment]
Yeah, I assume it would error without a default.

**Comment by ChrisRackauckas** [comment]
NamedTuples are immutable like tuples, right? That would make the "anonymous immutable" the same, but the "anonymous type" would be different.

**Comment by ChrisRackauckas** [comment]
Maybe a struct like in JuliaLang/julia#16580 is really the right thing for my application.

**Comment by mauro3** [comment]
Yep https://github.com/JuliaLang/julia/pull/16580 will be well cool to have.

Well, I don't have a use for this but would accept a PR (if it doesn't add too much complexity).

**Comment by ChrisRackauckas** [comment]
Closing this because the struct would be a better idea.
