### ISSUE TITLE
warning when redefining show, Julia >=0.5 only

### ISSUE THREAD

**Issue by stephancb** [mauro3/Parameters.jl#20]
Since Julia 0.5 I get (slightly annoying)

WARNING: Method definition show(IO, ....

when redefining the show function of a "with_kw" immutable:

```
julia> using Parameters

julia> @with_kw immutable Tstmp
           day2000::Int
           msec::Int
       end
Tstmp

julia> Base.show(io::IO, tt::Tstmp) = print(io, "days since 2000-01-01: $(tt.day2000) millisec of day: $(tt.msec)")
WARNING: Method definition show(IO, Main.Tstmp) in module Main at /home/scb/code/julia/pkg/v0.5/Parameters/src/Parameters.jl:375 overwritten at REPL[3]:1.
```

**Comment by mauro3** [comment]
Yes, this is expected and is hitting one of 0.5's more controversial features:
https://github.com/JuliaLang/julia/issues/18725

The `@with_kw` macro also defines a show method:
```
julia> type A
       a
       b
       end

julia> A(3,4)
A(3,4)

julia> @with_kw type B
       a
       b
       end
B

julia> B(3,4)
B
  a: 3
  b: 4
```
So if you define your own show method it will overwrite the one of `@with_kw` and trigger the warning.

Solutions: live with it or remove the show definition from the macro.

**Comment by stephancb** [comment]
Ok, thanks.

**Comment by mauro3** [comment]
One solution could be to have several macros, one of which, didn't make a `show` method.  But that does lead to quite a bit more complexity, which I'm hesitant to add.  I'll leave this open for now and ponder it some.

**Comment by mauro3** [comment]
Also you could use https://github.com/Ismael-VC/Suppressor.jl:
```
julia> using Parameters

julia> @with_kw immutable Tstmp
           day2000::Int
           msec::Int
       end
Tstmp

julia> @suppress_err Base.show(io::IO, tt::Tstmp) = print(io, "days since 2000-01-01: $(tt.day2000) millisec of day: $(tt.msec)")
```

**Comment by mauro3** [comment]
Closing this as "won't-fix" as I want to keep the automatically defined show methods.

**Comment by juliohm** [comment]
Could you please reconsider this issue? I really like the keyword parameters, but I also think that in many cases the user wants to write their own `Base.show`. Using another package for just hiding the warning seems like hmmm... :-1: 

I hope the issue won't be ported to Base. Keyword parameters are awesome without shows.

**Comment by ChrisRackauckas** [comment]
`@with_kw_noshow`?

**Comment by juliohm** [comment]
Wonderful!

**Comment by mauro3** [comment]
Ok.

**Comment by mauro3** [comment]
This still needs docs, so I'll keep it open for now.   But it works:
```
@with_kw_noshow struct A
a
end
```

**Comment by juliohm** [comment]
That is awesome @mauro3 , thanks for adding this feature :slightly_smiling_face:

**Comment by mauro3** [comment]
You're welcome!

**Comment by mauro3** [comment]
Now also has docs.
