### ISSUE TITLE
Combine `@with_kw` and `@def`

### ISSUE THREAD

**Issue by cortner** [mauro3/Parameters.jl#21]
I experimented with a `@def` macro I picked up from @ChrisRackauckas somewhere to share fields across multiple types.

```
macro def(name, definition)
    return quote
        macro $(esc(name))()
            esc($(Expr(:quote, definition)))
        end
    end
end

@def sharedparams begin
   A::Float64
   B::Int
end

type MyType
    @sharedparams 
end 

MyType(1.0, 1)
# OK
```

But then I tried to combine it with `@with_kw`:

```
using Parameters 

@def sharedparams begin
   A::Float64  = 1.0
   B::Int = 1 
end

@with_kw type MyType2 
    @sharedparams 
end 

MyType2()

# ERROR: Field '@sharedparams' has no default, supply it with keyword.
# in MyType2() at /Users/ortner/.julia/v0.5/Parameters/src/Parameters.jl:304  
```

What is the difficulty? Can this be worked around?

**Comment by ChrisRackauckas** [comment]
Interior macros would just have to be expanded before `@with_kw`'s parsing.

**Comment by mauro3** [comment]
@ChrisRackauckas's suggestion should work.  I'll look into it.

**Comment by cortner** [comment]
is there a temporary work-around?

**Comment by mauro3** [comment]
Copy-paste ;-)  

I'll look at it tomorrow and give you an estimate when I can fix it.

**Comment by mauro3** [comment]
@cortner: can you check whether this fix works for you?  There are limitations, in particular with nesting, see https://github.com/mauro3/Parameters.jl/blob/3d2bf5f7fb18530ffb62e7bf5a2a38a65ecc3dc0/test/runtests.jl#L439

**Comment by cortner** [comment]
yes, that seems to work on a first attempt. thank you for the quick fix.

**Comment by mauro3** [comment]
Now released.
