### ISSUE TITLE
Enable to decorate kw-constructor with a macro

### ISSUE THREAD

**Issue by ChrisRackauckas** [mauro3/Parameters.jl#23]
Is it possible to mark the default constructor from `@with_kw` as pure?

**Comment by mauro3** [comment]
I still don't quite get the use of `@pure`.  Is there any documentation on it?  So, presumably you're in a better position to answer your question.

**Comment by ChrisRackauckas** [comment]
I don't know if it's documented. I know that in some cases you will want to mark a constructor as pure. I was wondering if it could be implemented:

```julia
@with_kw type MyType{T}
  my_immutable::T = OtherPureConstructor()
end pure=true
```

Even better, a way to make default extra parameters:

 ```julia
@with_kw type MyType{T,true}
  my_immutable::T = OtherPureConstructor()
end pure=true
```

**Comment by mauro3** [comment]
If this would need a switch, then I'd rather not have it (feature creep and such).  You know that you can hand-code the positional constructor and everything works as it should:
```julia
@with_kw type MyType{T}
  my_immutable::T = OtherPureConstructor()
  @pure MyType(mi) = new(mi)
end 
```
(Actually that doesn't currently work but I'll fix that)
But presumably `MyType` has many fields making this a nuisance?  Although using `macroexpand` you can copy-paste it.

I don't get the meaning of your second example.

(PS: there is some "documentation" here: https://github.com/JuliaLang/julia/issues/14324)

**Comment by ChrisRackauckas** [comment]
>I don't get the meaning of your second example.

A default for the second type parameter, set to true.

**Comment by ChrisRackauckas** [comment]
>You know that you can hand-code the positional constructor and everything works as it should:

The reason to do this is for the keyword argument constructors. If it's on immuable kwargs and those carry type information, it's the result is not inferred unless you `Base.@pure`.

**Comment by ChrisRackauckas** [comment]
>Is that linked to the true in pure=true?

No, should be a separate example:

```julia
@with_kw type MyType{T,true}
 my_immutable::T = OtherPureConstructor()
end
```

Same as

```julia
MyType(;my_immutable=OtherPureConstructor(),T2=true) = MyType{typeof(my_immutable),T2}(my_immutable)
```

which won't infer without `Base.@pure`.

**Comment by mauro3** [comment]
I'll need to think about the default parameters: #24.

>> You know that you can hand-code the positional constructor and everything works as it should:

> The reason to do this is for the keyword argument constructors. If it's on immuable kwargs and those carry type information, it's the result is not inferred unless you `Base.@pure.`

Ah, you need to mark the keyword constructor with `@pure`.  I kinda see the kw-constructor as a performance killer anyway, so it seems a bit strange to enhance it with `@pure`, no?

**Comment by ChrisRackauckas** [comment]
>I kinda see the kw-constructor as a performance killer anyway, so it seems a bit strange to enhance it with @pure, no?

No, because it's actually compile-time inferred if the kwargs are immutable in this case and you mark it as `Base.@pure`, so there's no reason for it to kill performance for many type constructors.

**Comment by mauro3** [comment]
I tried this example:
```julia
f(;i=1) = i
ff(;i::Int=1) = i
Base.@pure fp(;i=1) = i
Base.@pure fpp(;i::Int=1) = i

testfn(ff) = ff(i=3) + 7
@code_warntype testfn(f) # Any
@code_warntype testfn(ff) # Int
@code_warntype testfn(fp) # Any
@code_warntype testfn(fpp) # Int
```
but no effect (although I was surprised to se `ff` inferred).  Can you give me a runnable example?

**Comment by ChrisRackauckas** [comment]
>Can you give me a runnable example?

I am surprised `fp` didn't infer. I know I tested this before:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/algorithms.jl#L42

and these were inferring. Maybe it's just for type parameters? Though it should also work on fields. Sounds like a bug... which at least would be fixed with the `Struct` PR.

**Comment by mauro3** [comment]
I had another look at this and played with the code you linked above.  It boils down to the type parameters you use there.  Example:
```julia
immutable Tp{A} end
Base.@pure Tp(;A=1) = Tp{A}()
@code_warntype Tp() # inferred (not inferred in Julia 0.6!)
@code_warntype Tp(A=5) # not

immutable Tn{A} end
Tn(;A=1) = Tn{A}()
@code_warntype Tn() # not
@code_warntype Tn(A=5) # not
```
So, when using `@pure`, calling the constructor without kwords is inferred (but only in Julia 0.5, not 0.6).  However note that when calling with kwords, none are inferred.  So, I'm a bit doubtful this optimization is worth it. (Note, adding a type annotation `Base.@pure Tp(;A::Int=1) = Tp{A}()` does not help either.)

Anyway, the question remains: should there be a way to decorate the kw-constructor with a macro?  Unless we find a intuitive, general syntax for this, I'm hesitant to add this feature.

**Comment by mauro3** [comment]
Update for Julia 0.7:
```julia
              _                                                                                                                                                         
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.5095 (2018-05-12 22:13 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 2a21849b10* (0 days old master)
|__/                   |  x86_64-pc-linux-gnu

julia> struct Tp{A} end
                                   
julia> Tp(;A=1) = Tp{A}()
Tp
               
julia> @code_warntype Tp() # inferred

julia> @code_warntype Tp(A=5) # not, addin @pure does not help either
```
using the `Val` trick works:
```
julia> struct Tpp{A} end           

julia> Tpp(;a::Val{A} = Val(4)) where A = Tpp{A}()
Tpp

julia> Tpp(a=Val(4))
Tpp{4}()

julia> @code_warntype Tpp(a=Val(4)) # inferred
```
@ChrisRackauckas: can I close this or is there still a need for `@pure` annotation?

**Comment by mauro3** [comment]
I'll close this for now.  Please, re-open if still needed.
