### ISSUE TITLE
renaming slots in @unpack

### ISSUE THREAD

**Issue by tpapp** [mauro3/Parameters.jl#26]
When unpacking two composite types with the same (or overlapping) field names, it would be nice to rename the variables. Eg with the syntax
```julia
@unpack (domain_a=a), (domain_b=b) = domain
@unpack (range_a=a), (range_b=b) = range
```
but I admit the syntax above is awkward. Cf [COMMON-LISP:WITH-SLOTS](http://clhs.lisp.se/Body/m_w_slts.htm), for slot forms of `(variable-name slot-name)`.

**Comment by mauro3** [comment]
Thanks for the feedback! However, I think by that point you might as well write it out.  Also, I'd like to keep the code readable for someone who doesn't know Parameters.jl, this definitely does not qualify.

**Comment by mauro3** [comment]
I'll close this as "won't fix".  But please reopen, if you feel your concerns have not been addressed.
