### ISSUE TITLE
A better package name

### ISSUE THREAD

**Issue by mauro3** [mauro3/Parameters.jl#3]
`Parameters.jl` is bad.  Maybe better `DefaultValues`, `DefaultFieldValues`?  Any ideas?

**Comment by damiendr** [comment]
I like `DefaultValues`.

**Comment by mauro3** [comment]
Maybe go big: `ConvenientTypes`

**Comment by damiendr** [comment]
Another linguistic option to explore is `traits`, in reference to the concept of *object-properties-with-defaults-and-validation* in the Python ecosystem.

http://code.enthought.com/projects/traits/
https://github.com/ipython/traitlets

**Comment by mauro3** [comment]
That would probably be confusing in light of https://github.com/mauro3/Traits.jl

**Comment by gabrielgellner** [comment]
`KWTypes` ?

**Comment by mauro3** [comment]
In #13 we're discussing to split the package into to keyword-constructor part and a unpack part.  Names could be `KWTypes` and `Unpack`.  Thoughts?

**Comment by ChrisRackauckas** [comment]
That sounds like a good idea. They are pretty different functionality and those names are more specific. Though at the same time, there isn't a pressing need to pull them apart because this is already a very lightweight dependency.

**Comment by mauro3** [comment]
True, there is no hurry.  However, the introduction of breaking changes discussed in #13 would be a good time for the split.

**Comment by gabrielgellner** [comment]
The package name `Unpack` feels unmotivated to me if it is not part of `KWTypes` as unpack is such a general description (though I like the names for the macros themselves). Is something like `KWUnpack` too ugly? Makes the synergy of these packages more transparent. That being said, what is the benefit of decoupling these? Is it a real developer savings? Is it just that the name `KWTypes` sounds weird if the user just wants to do unpacking? Would `KWTypeTools` be a better unified name?

I guess my only worry is that it feels like premature optimization to turn this into two tiny packages. The benefit is not really clear to me beyond being really stringent on modularity versus usability. I worry, in general, that the Julia community is getting crazy into making packages of almost single functions, were everything needs to be explicitly imported at a crazy fine scale (brings back dark memories of java like python packages with imports like `import foo.foo` where some module in a package have the same name and you need to double everything up for some weird vision of clean namespaces...)

**Comment by mauro3** [comment]
The motivation to split them is that `@unpack` etc can be used for any type (and dict once #13 is merged).  So no real connection with the kw-constructors/default values, except that you might well use them combined.

But it is a fair point, no need to split them now, especially as both parts are tiny.

**Comment by gabrielgellner** [comment]
Super excited for #13 by the way ... have been meaning to do something like this for a while :)

**Comment by mauro3** [comment]
Ok, I'll leave the package as is for now.  As it includes both kw-types and (un)pack, `Parameters.jl` is not that bad a name.  If it gets split at some point we can revisit.
