### ISSUE TITLE
construct a parameter from a json file

### ISSUE THREAD

**Issue by floswald** [mauro3/Parameters.jl#33]
hi there,

i often end up with a json file that holds all the parameters, a description, and a tex symbol maybe. for example i used to do (julia 0.5):

```julia
type Param
    gamma   :: Float64

    "Constructor of Param type"
    function Param()
        f=open(joinpath(dirname(@__FILE__),"params.json")) 
        j = JSON.parse(f)
        close(f)
        this = new()
        for (k,v) in j
            setfield!(this,Symbol(k),v["value"])
        end
        return this
    end
end
```

and a param file

```json
{
	"gamma" : {
		"value" : 0.3,
		"description" : "curvature parameter",
		"type" : "exogenous",
		"symbol" : "\\gamma"
	}
}
```

the advantage of this is that if I want to change the value of a parameter I don't have to reload the package, but just change the value in the json. also having all the param info in one place is good. anway, in julia 0.6 i can do this only by saying that `Param` should be a `mutable struct`, which seems wrong. any idea I could use `Parameters.jl` to populate a parameter type form a file? (importantly, I don't want this to rely only on the *ordering* of parameters in the json file, but an actual key). thanks!

**Comment by mauro3** [comment]
Can you make a `Dict{Symbol,Any}` from the json file? Then:
```julia
@with_kw struct Param
    gamma   :: Float64
end

pa = Param(;dict_from_json...)
```

Also concering:
> The advantage of this is that if I want to change the value of a parameter I don't have to reload the package, but just change the value in the json. 

You can then do:
```
pa_new = Param(pa; gamma = 2)
```

**Comment by mauro3** [comment]
I'll close this.  Just post here if you got more questions.  Or re-open if you think it needs resolving.
