### ISSUE TITLE
wishlist: allow @argcheck instead of @assert

### ISSUE THREAD

**Issue by tpapp** [mauro3/Parameters.jl#34]
Parameters.jl and [ArgCheck.jl](https://github.com/jw3126/ArgCheck.jl) are two staple packages I always use for code. I like how `@argcheck` allows more meaningful error messages. I wonder if `@with_kw` could also collect `@argcheck` forms into the constructor, in addition to `@assert`.

**Comment by mauro3** [comment]
Yes, that should be fine. I don't use ArgCheck.jl myself, but PR is welcome.

**Comment by mauro3** [comment]
There seems to be something brewing with `@assert`: https://github.com/JuliaLang/julia/pull/25576#issuecomment-358358758

**Comment by singularitti** [comment]
One thing that blocks to insert `@argcheck` is that `@argcheck` will be expanded to a `begin` block that is [forbidden by `with_kw`](https://github.com/singularitti/Parameters.jl/blob/77575a3/src/Parameters.jl#L443-L444).

```julia
julia> @macroexpand @argcheck 2 > 1
quote
    $(Expr(:meta, :begin_optional, ArgCheck.LabelArgCheck()))
    begin
        var"#130###302" = (>)
        var"#131###303" = 2
        var"#132###304" = 1
        if var"#130###302"(var"#131###303", var"#132###304")
            ArgCheck.nothing
        else
            ArgCheck.throw(ArgCheck.build_error(ArgCheck.CallErrorInfo($(QuoteNode(:(2 > 1))), ArgCheck.ArgCheckFlavor(), $(QuoteNode(Any[:>, 2, 1])), [var"#130###302", var"#131###303", var"#132###304"], ())))
        end
    end
    $(Expr(:meta, :end_optional, ArgCheck.LabelArgCheck()))
end
```
