### ISSUE TITLE
Unable to provide docstrings

### ISSUE THREAD

**Issue by cstjean** [mauro3/Parameters.jl#4]
Perhaps a known issue: 

```julia
""" Documentation! """
@with_kw immutable Foo2
    x
end

LoadError: invalid doc expression:

@doc "..." @with_kw immutable Foo2
        $(Expr(:line, 3, symbol("In[10]")))
        x
    end

'@with_kw' not documentable. See 'Base.@__doc__' docs for details.
```
I'm not sure if this is solvable given the error message, but function definitions preceded by macro calls can be documented, so I assume that there's a way.

Thank you for Parameters.jl, it's very convenient.

**Comment by mauro3** [comment]
Yes, known indeed!  I actually filed the issue in Julia (https://github.com/JuliaLang/julia/issues/12705)  to make this possible but then forgot to implement it... I'll get to it over the next few days.  (it will only work on 0.4 though)

**Comment by cstjean** [comment]
Awesome, thank you!
