### ISSUE TITLE
Support named tuples

### ISSUE THREAD

**Issue by mauro3** [mauro3/Parameters.jl#41]
Named tuples just landed in Julia 0.7.  Think about supporting them:

- `@unpack`
- `reconstruct`

**Comment by tpapp** [comment]
I think this would be a very useful addition to the package, extending existing syntax.

**Comment by tpapp** [comment]
It seems to work out of the box on the current `master` that will become `v0.7`.
```julia
julia> using Parameters
INFO: Precompiling module Parameters.
function f(x)
julia> function f(x)
       @unpack a, b = x
       a+b
       end
f (generic function with 1 method)

julia> t = (a=1, b=2)
(a = 1, b = 2)

julia> f(t)
3

julia> VERSION
v"0.7.0-DEV.2949"
```
I guess all it needs are some unit tests. And we need an issues label "magic" :smile:
