### ISSUE TITLE
`@pack_*` does not mutate struct

### ISSUE THREAD

**Issue by pelagisk** [mauro3/Parameters.jl#46]
From the following code:

```julia
@with_kw mutable struct S
    a::Int = 1
    b::Float64 = 2.0
end

function f(s::S)
    @unpack_S s
    a = 2
    @pack_S s
end

function g(s::S)
    s.a = 2
end

s = S(b=3.0)

println(s)
f(s)
println(s)
g(s)
println(s)
```

I would expect `@pack_*`, `@pack_*` to know that the struct is mutable and do the same thing in functions `f` and `g`, but `f` does not mutate the struct!

```julia
S
  a: Int64 1
  b: Float64 3.0

S
  a: Int64 1
  b: Float64 3.0

S
  a: Int64 2
  b: Float64 3.0
```

Is this expected behaviour?

**Comment by pelagisk** [comment]
However, both of these work:

```julia
setfield!(s, :a, 2)
```

```julia
a = 2
@pack s = a
```

So does `@pack_S s` if I use it in the REPL, but not in a function!

**Comment by mauro3** [comment]
Ok, check out the latest master.  I think is should do what you expect.

**Comment by pelagisk** [comment]
It does indeed, using `@pack!_*` that is. Great!

**Comment by ronisbr** [comment]
Hi @mauro3 ,

Do you have any plans to release a new version of Parameters.jl with this function? I would like to use this in my package.

Thanks!
