### ISSUE TITLE
Problem with stepping over(debugging) @pack macro from Parameters module

### ISSUE THREAD

**Issue by TsurHerman** [mauro3/Parameters.jl#47]
MWE:
```

using Parameters
using ASTInterpreter2

d1= Dict("a"=>1,"b"=>2,"c"=>3)
f(d) = begin
    @unpack a,b,c = d
    a+b+c
end
@enter f(d1)
```
I opened a similar[ issue](https://github.com/Keno/ASTInterpreter2.jl/issues/18) in ASTInterpreter2

**Comment by mauro3** [comment]
What happens if you write it out by hand?

**Comment by TsurHerman** [comment]
If I write it by hand it works flawlessly...
So there is a workaround .. but I find it very hard to part with the compactness and elegance that @pack @unpack add to my code :-) .
I think ASTInterpreter2 can skip some macros for example @__DIR__   But not all macros.

This issue is intended as reference for fixing “some day” as I consider both Parameters and Debugging essential for the language.

**Comment by mauro3** [comment]
I'll close this for now as the debugger isn't working anyway, afaik.
