### ISSUE TITLE
Human-readable file

### ISSUE THREAD

**Issue by grahamas** [mauro3/Parameters.jl#48]
It would be very useful to be able to write out the parameter struct to a human-readable file, and then to be able to automatically read in the same. So:
```
@with_kw struct A
    ...
end
an_instance = A(args...)
Parameters.tofile(an_instance, "instance_file.txt")
identical_instance = Parameters.fromfile(A, "instance_file.txt")
```
This should be relatively easy to do using show. There are just a couple potential problems:
- This means `@with_kw_noshow` can't save in this method. But they still have JLD? Or can provide their own show function? So this should be fine.
- I see two things in show's implementation that raise red flags: `:limit => true` and `maxdepth=1`. 

I would be happy to make a PR for this. However, I can't find any documentation on `dump` and without that, I'm flying blind (the [source](https://github.com/JuliaLang/julia/blob/d386e40c17d43b79fc89d3e579fc04547241787c/base/docs/helpdb/Base.jl#L530-L534) the docs point to is quite unhelpful). If someone can direct me to proper documentation for `dump`, I'd be happy to take a stab at a PR.

edit: From discussion [here](https://discourse.julialang.org/t/model-configuration-parameterization-file/8982/6?u=grahamas).

**Comment by mauro3** [comment]
Thanks for the feedback! I think that storing/loading of a type to a text file can and should work for any type, irrespective of whether it is constructed using Parameters.jl or not.  What might be nice is some compact representation of `A` to store in a info-file, summarizing a bunch of model runs.

**Comment by grahamas** [comment]
I wondered about that when I was typing the example code. The `@with_kw` seemed superfluous. This is really just an inverse of `dump` for a struct. Do you have any recommendation about where this issue should go? Or does such an inverse already exist?

**Comment by grahamas** [comment]
With respect to your suggested alternative, that also feels a bit beyond the scope of your Parameters.jl, no? A very similar version of that idea, and one project I've been interested in implementing, would be a database keyed on parameters containing run results (or some function of run results, more likely).

Mainly I think those might be beyond the scope of your package because I remain shocked that your package hasn't been eaten by Julia into a language feature. It seems to me far more general than just model parameters (though that is also what I use it for...). Is there an issue in Julia to integrate Parameters.jl with the language yet? On the other hand, your suggestion and mine step beyond these generally useful features into features that are very specifically useful for modeling.

Sorry, I've gone a bit far afield. Feel free to close me whenever you'd like, preferably with a pointer to a better place to implement my to-fromfile functions.

**Comment by mauro3** [comment]
I'll close this.  There was this [discoure](https://discourse.julialang.org/t/computational-experiments-organising-different-algorithms-their-parameters-and-results/10774/3) which might be slightly relevant.
