### ISSUE TITLE
Feature request: pack/unpack all

### ISSUE THREAD

**Issue by fisherc2** [mauro3/Parameters.jl#51]
In many cases, I want to extract all of the values from an object and assign them to variables with the same name as their fieldnames. It would be convenient if the macro assigned the variables automatically in this manner unless specified otherwise. Here is an example of what I have in mind:

```
mutable struct MyStruct 
    x::Float64
    y::Float64
    z::Float64  
end 

parms = MyStruct(45.3,.3,.78) 

function model(parms)
    @unpack parms
    val = (x+y)^z
end
```

**Comment by mauro3** [comment]
If you use `@with_kw` then a specific unpack for a type is constructed:
https://mauro3.github.io/Parameters.jl/latest/manual.html#The-type-specific-(un)pack-macros-(somewhat-dangerous)-1

In general this cannot be done as it is not possible to evaluate into a local scope in Julia. I'll close this for now, but keep posting here.  Or re-open if you feel I did not address your request.

**Comment by fisherc2** [comment]
Thanks. Sorry I didn't quite understand the @unpack_* when I initially read the documentation. Thats exactly what I was looking for.  Are there any plans to improve the shadowing/naming conflict behavior? Aside from that issue, it seems like it would be a very useful utility.

**Comment by mauro3** [comment]
> improve the shadowing/naming conflict behavior

I don't think that is possible, so that is just the risk you take.  I usually use the explicit form, at least for code I plan to keep around for a bit.

**Comment by fisherc2** [comment]
Bummer. Well, thanks for the clarification and providing this package.
