### ISSUE TITLE
Add sugar for constraints

### ISSUE THREAD

**Issue by mauro3** [mauro3/Parameters.jl#6]
Should sugar be added for constraints? Ref: https://github.com/JuliaLang/METADATA.jl/pull/4114

Currently one can write:
```julia
@with_kw type StructName
  field_name::field_type
  fname2::ftype2 = default_val2
  fname3::ftype3 = default_val3
  function StructName(field_name, fname2, fname3)
    @assert fname2 > 0 && fname2 < 5
    @assert fname3 <= fname2
    new(field_name, fname2, fname3)
  end
end
```

If sugar is called for, the question is whether they should be line by line:
```julia
@with_kw type StructName
  field_name::field_type
  (fname2::ftype2 = default_val2, fname2 > 0 && fname2 < 5)
  (fname3::ftype3 = default_val3, fname3 <= fname2)
end
```
or just as separate block(s):
```julia
@with_kw type StructName
  field_name::field_type
  fname2::ftype2 = default_val2
  fname3::ftype3 = default_val3
  @constraints fname2 > 0 && fname2 < 5, fname3 <= fname2
end
```
I think I would favor the second as constraints are in general not tied to a particular field. Plus its possible to make it look like the first version:
```julia
@with_kw type StructName
  field_name::field_type
  fname2::ftype2 = default_val2; @constraints fname2 > 0 && fname2 < 5
  fname3::ftype3 = default_val3; @constraints fname3 <= fname2
end
```

**Comment by cstjean** [comment]
+1 for `@constraints`

**Comment by mauro3** [comment]
@Evizero: I don't have time to implement this just now, probably January (this is not something I use often, so less personal motivation). I like the second syntax better, so let's do that. (Plus there is already macro-in-macro syntax with `@deftype`).  If you need it now, either use above non-sugared constraints, SimpleStructs or submit a PR (preferred).

**Comment by Evizero** [comment]
Thanks for responding. Yes, that's very understandable. I don't think I will put in the time to actually work on this, as my plate is also pretty full already.

**Comment by mauro3** [comment]
I decided to just use `@assert` inside the type-def.  No need for a "new" macro.
