### ISSUE TITLE
Support for memos

### ISSUE THREAD

**Issue by cstjean** [mauro3/Parameters.jl#7]
I often have types like

```julia
@with_kw type Foo
   x
   memo=nothing
end
```
Where memo will be used to store some long computation of x. This is incompatible with `@with_kw`, since a call to `Foo(f, x=10)` should set the memo of the new object to `nothing`.

Solution 1:

```julia
@with_kw type Foo
   x
   (memo=nothing; copied=false)
end
```

Solution 2:
```julia
@with_kw (copy_constructor_name=:copy_Foo) type Foo
    x
    memo=nothing
end
Foo(args...; kwargs...) = copy_Foo(args...; memo=nothing, kwargs...)
```

Or something else?

It would be even more awesome to be able to specify the caching behavior directly. Suppose I want to cache the result of some function called LongComputation:

```julia
@with_kw type Foo
    x
    @memo LongComputation
end
@show LongComputation(Foo(10))  # automatically stores the result inside Foo
```
But that's more work, and I'm not sure that it's possible given Julia's function dispatch.

**Comment by mauro3** [comment]
Thanks for the report.  To avoid too much feature creep, I will give this one a miss, sorry!

However, this should work:
```julia
@with_kw type Foo
   x
   memo=nothing
end
Foo(pp::Foo; kws...) = (push!(kws, (:memo, nothing)) ; reconstruct(pp,kws))
```
gives:
```
julia> f = Foo(x=4, memo=2)
Foo
  x: 4
  memo: 2

julia> Foo(f)
Foo
  x: 4
  memo: nothing
```
However, there is this bug:
```
julia> Foo(f, memo=77)
Foo
  x: 4
  memo: nothing
```
if that is an issue you'll have to be a bit more verbose in that function definition.

**Comment by cstjean** [comment]
The `reconstruct` solution is perfect, thank you!

**Comment by mauro3** [comment]
Cool
