### ISSUE TITLE
how to deprecate a field

### ISSUE THREAD

**Issue by bjarthur** [mauro3/Parameters.jl#72]
is there a way to deprecate a field?  specifically, is there a way to mimic this code:

```
struct AB
    a
    b
end

function AB(a,b)
    depwarn("b is deprecated", :AB)
    return AB(a)
end
```

**Comment by mauro3** [comment]
No, there is none.  You'd have to hand-code the inner positional constructor.  Maybe #52 could work for this.

**Comment by mauro3** [comment]
Adding the example to #52 and closing.
