### ISSUE TITLE
struct vs mutable struct in docs

### ISSUE THREAD

**Issue by AshtonSBradley** [mauro3/Parameters.jl#74]
Not so much an issue as a suggestion for docs updates. 

If I run the example
```julia
@with_kw struct Para{R<:Real}
    a::R = 5
    b::R
    c::R = a+b
end
pa = Para(b=7)
```
and then try the `@pack` macro example (also please note fn2 <-> fn1 typo in docs)
```julia
function fn2(var, pa::Para)
    @unpack a, b = pa # equivalent to: a,b = pa.a,pa.b
    out = var + a + b
    b = 77
    @pack pa = b # equivalent to: pa.b = b
    return out, pa
end

out, pa = fn2(7, pa)
```
I get
```julia
type is immutable

Stacktrace:
 [1] macro expansion at /Users/abradley/.julia/v0.6/Parameters/src/Parameters.jl:807 [inlined]
 [2] fn2(::Int64, ::Para{Int64}) at ./In[20]:11
```

fixed by

```julia
@with_kw mutable struct Para{R<:Real}
    a::R = 5
    b::R
    c::R = a+b
end
```

**Comment by mauro3** [comment]
Thanks for the report.  I updated the docs slightly, maybe better?   The diff:
https://github.com/mauro3/Parameters.jl/commit/49ad1e1c295aa6b65681fa6abdddf9657553250e

Although, I don't think it is Parameters.jl task to teach about immutable vs mutable.  Please re-open if you feel this has not been addressed properly.
