### ISSUE TITLE
Implement compact show method for new types

### ISSUE THREAD

**Issue by juliohm** [mauro3/Parameters.jl#75]
Currently if we use the package, the `show` methods are nicely defined for the type, however a compact version is missing:

```julia
using Parameters

@with_kw struct Foo
  a = 1
  b = 2
  c = 3
end

[Foo() for i=1:3]

3-element Array{Foo,1}:
 Foo
  a: Int64 1
  b: Int64 2
  c: Int64 3

 Foo
  a: Int64 1
  b: Int64 2
  c: Int64 3

 Foo
  a: Int64 1
  b: Int64 2
  c: Int64 3

```

Could you please implement a compact show method so that whenever we have a list of objects, we have a one-liner message?

**Comment by mauro3** [comment]
Sure, but PR welcome.

**Comment by juliohm** [comment]
Thanks, I can try look into it after Tuesday or next week.

**Comment by juliohm** [comment]
@mauro3 could you please help with this issue? Any hints?

**Comment by mauro3** [comment]
I'm on vacation until 22 Oct and will get back to you then.  Ping me if I forget!

**Comment by juliohm** [comment]
@mauro3 too busy? Sorry pinging again

**Comment by mauro3** [comment]
Yep, a bit busy.  I'll need to read up on the show-compact stuff first.

**Comment by mauro3** [comment]
Would this work for you:
```
julia> [Foo() for i=1:3]
3-element Array{Foo,1}:
 Foo(1, 2, 3)
 Foo(1, 2, 3)
 Foo(1, 2, 3)

julia> [Foo() for i=1:3, j=1:5]
3×5 Array{Foo,2}:
 Foo(1, 2, 3)  Foo(1, 2, 3)  Foo(1, 2, 3)  Foo(1, 2, 3)  Foo(1, 2, 3)
 Foo(1, 2, 3)  Foo(1, 2, 3)  Foo(1, 2, 3)  Foo(1, 2, 3)  Foo(1, 2, 3)
 Foo(1, 2, 3)  Foo(1, 2, 3)  Foo(1, 2, 3)  Foo(1, 2, 3)  Foo(1, 2, 3)
```
?

**Comment by mauro3** [comment]
You can check it out in #93.

**Comment by juliohm** [comment]
Beautiful! :heart: 

Thank you @mauro3 for the addition! Please feel free to merge. I can then test it with my own types and report it if something is not working.

**Comment by mauro3** [comment]
Cool.  Maybe you can give it a try on master and if all ok, I'll tag a release.

**Comment by juliohm** [comment]
@mauro3 this is how I am calling the show method on my parameter types: https://github.com/juliohm/GeoStatsDevTools.jl/blob/master/src/macros.jl#L101

It is still producing the long version, am I doing something wrong?

I am on master now `] dev Parameters`

**Comment by mauro3** [comment]
This works for me:
```
julia> @with_kw struct AA
       a = 1; b=1
       end
AA

julia> show(IOContext(stdout, :compact => true), AA())
AA(1, 1)
julia> show(IOContext(stdout, :compact => false), AA())
AA
  a: Int64 1
  b: Int64 1
```

**Comment by juliohm** [comment]
I'll investigate it carefully later today. Thank you. Heading to work...

**Comment by juliohm** [comment]
@mauro3, it is not working for my types:

```julia
using Variography
show(IOContext(stdout, :compact => true), GaussianVariogram())

GaussianVariogram{Float64,Euclidean}
  range: Float64 1.0
  sill: Float64 1.0
  nugget: Float64 0.0
  distance: Euclidean
```

**Comment by mauro3** [comment]
Can you post a MWE?

**Comment by juliohm** [comment]
Thanks, MWE below:

```julia
using Parameters

abstract type V{T,D} end

@with_kw struct G{T,D} <: V{T,D}
  a::T = 1.
  b::T = 1.
  c::T = 0.
  d::D = 1
end

show(IOContext(stdout, :compact => true), G())
```

**Comment by mauro3** [comment]
Thanks! But no I get the output:
```
julia> show(IOContext(stdout, :compact => true), G())
G{Float64,Int64}(1.0, 1.0, 0.0, 1)
```

Are you sure you're on master?  Maybe the project you're in is using the latest release even though you did do `dev Parameters` elsewhere?

**Comment by juliohm** [comment]
When I do `] st` I get the following for Parameters.jl:

```
[d96e819e] Parameters v0.10.2+ [`~/.julia/dev/Parameters`]
```

And the local repo is on the `master` branch.

**Comment by juliohm** [comment]
This has anything to do with the Julia version?
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

**Comment by mauro3** [comment]
I am on Julia 1.0.2, but that would be odd.

That Pkg-status looks ok. What is the last commit you got in Parameters?  It should be
```
commit 870131fa4114af141b4c40d8275259e5d19e444b (HEAD -> master, origin/master)
Author: Mauro
Date:   2018-12-12 10:23:06 +0000

    Compact show, fix #75 (#93)
```

**Comment by juliohm** [comment]
For some reason `dev` was not pulling the latest commits o.O

I did a manual `git pull` and it is working beautifully. Thank you! Do you mind creating a new release?

**Comment by mauro3** [comment]
That is a bit odd.  Was you're repo dirty? Well, it's sorted now.

BTW, compact printing of types with lots of fields will still take a significant amount of horizontal space.  But I think that would be more of a Julia issue, not Parameters specific.

I'll tag.

**Comment by cstjean** [comment]
FWIW, in QuickTypes, `_concise_show` also takes out the `{}` parameters for parametric types, and I find that it improves readability significantly.

**Comment by juliohm** [comment]
Also I'm using ththe unpack feature of Parameters.jl

**Comment by cstjean** [comment]
> I wonder if it handles all use cases of Parameters.jl?

No, not at the moment. In addition to the unpacking you mentioned, Parameters.jl also has a "copy constructor", which is very convenient (although there's SetField.jl). Plus, the `@with_kw` syntax is more readable for longer type definitions.
