### ISSUE TITLE
reset?

### ISSUE THREAD

**Issue by BeastyBlacksmith** [mauro3/Parameters.jl#81]
I just wrote this to set back a type to its default values:
```julia
function reset( m::T ) where T
    null = T()
    for name in fieldnames( T )
        setfield!( m, name, getfield( null, name ) )
    end
end
```
I mean, this would have to be modified to hold for types that don't have all all default values and maybe have a trait for immutables but maybe something like this would fit in this package?

**Comment by mauro3** [comment]
I'm not sure of the usefulness of this.  So closing.  Thanks for the feedback!
