### ISSUE TITLE
@pack!_<Struct Name> is not defined

### ISSUE THREAD

**Issue by ronisbr** [mauro3/Parameters.jl#82]
Hi @mauro3 ,

With the latest version of Parameters.jl, this code is not working:

```julia
using Parameters

@with_kw mutable struct Teste
    a
    b
    c
end

function teste()
    t = Teste(1,2,3)

    @unpack_Teste t

    a = 2

    @pack!_Teste t
end
```

The error is:

```
ERROR: LoadError: LoadError: UndefVarError: @pack!_Teste not defined
Stacktrace:
 [1] top-level scope
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] include(::String) at ./client.jl:388
 [6] top-level scope at none:0
in expression starting at /Users/ronan.arraes/tmp/teste.jl:16
in expression starting at /Users/ronan.arraes/tmp/teste.jl:9
```

If I changed `@pack!_Teste` to `@pack_Teste`, then it works, but I got the following warning:

```
┌ Warning: The macro `@pack_Teste!` is deprecated, use `@pack_Teste`
│   caller = ip:0x0
└ @ Core :-1
```

**Comment by mauro3** [comment]
The macro is called `@pack_Test!` and not `@pack!_Test`.  But I'm not sure whether it was called `@pack!_Test` at some stage and I did not deprecate it properly.  Is that the case?

**Comment by ronisbr** [comment]
Yes, this is probably what happened. Because this code works perfectly using Parameters.jl v0.9.2 without any warning. The syntax `@pack!_*` is also mentioned in the manual:

https://mauro3.github.io/Parameters.jl/latest/manual.html#The-type-specific-(un)pack-macros-(somewhat-dangerous)-1

**Comment by mauro3** [comment]
Ok, fixed in the latest docs. The stable will need to wait until I tag another release.  Thanks!
