### ISSUE TITLE
[suggestion/question] Print to LaTeX tables

### ISSUE THREAD

**Issue by briochemc** [mauro3/Parameters.jl#84]
I would love to be able to do something like 
```julia
LatexPrint(p)
```
that would print a LaTeX table (`tabular`) of the parameters and their values. Does this already exist?Even better would be to be combined with, e.g., @rafaqz's package [FieldMetadata.jl](https://github.com/rafaqz/FieldMetadata.jl) so that metadata (things like LaTeX symbols, units, ranges, citations, etc.) could also be added to the LaTeX table. I saw already-made packages ([LatexPrint.jl](https://github.com/scheinerman/LatexPrint.jl) from @scheinerman and @tpapp's [LaTeXTabulars.jl](https://github.com/tpapp/LaTeXTabulars.jl)), which I think may already provide most of the machinery needed, but I thought I'd ask here if maybe someone already worked such a LaTeX printing functionality for Parameters.jl, and suggest it otherwise.

**Comment by mauro3** [comment]
Wouldn't this rather be something you'd do with a DataFrame?

**Comment by rafaqz** [comment]
@briochemc the FieldMetadata.jl/Flatten.jl combo makes this composable so you don't need the dataframe. But this isn't a common pattern in other packages!

Defaults.jl can be used to do this if you need it and can afford to lose some Parameters.jl functions, but I've already suggested that to you...

**Comment by mauro3** [comment]
Note that https://github.com/jverzani/Mustache.jl can be used for this.  There is a nice example in the README. Also related https://discourse.julialang.org/t/ann-prettytables-jl-print-formatted-tables-in-julia/19550.
