### ISSUE TITLE
warning doesn't seem needed

### ISSUE THREAD

**Issue by AshtonSBradley** [mauro3/Parameters.jl#88]
Is there any way to turn off the unnecessary warning caused by `@pack_Something`:
```julia
┌ Warning: The macro `@pack_Something!` is deprecated, use `@pack_Something`
│   caller = ip:0x0
└ @ Core :-1
```
The warning is about syntax that is not used.

**Comment by mauro3** [comment]
Ok, sorry, the deprecation warning is wrong, it should read:
``The macro `@pack_Something` is deprecated, use `@pack_Something```

**Comment by AshtonSBradley** [comment]
do you mean `@pack_Something!` should be used? (missing `!` above?)

**Comment by mauro3** [comment]
Yes.  (Edited above)  The idea is that it mutates, thus a `!`.
