### ISSUE TITLE
Documentation: Dict{String, Any}

### ISSUE THREAD

**Issue by Datseris** [mauro3/Parameters.jl#90]
Hi,
I've noticed that `@pack! , @unpack` work just as well with `Dict{String, Any}` as they do with `Dict{Symbol, Any}`. Is there any reason that you explicitly mention only the `Symbol` one? 

FileIO does not work with symbols as names, you can't just do `save("file.jld2", dictionary)` if the keys are symbols. But it does work with Strings.

If there is no specific reason to forbid using Dict{String} (even though it works fine), then please consider re-working the docstrings to avoid other users being confused and having to check whether Dict{String} works.

**Comment by mauro3** [comment]
Thanks!
